// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-i_VIZBY8ch_4e9ESofx3GKOHNyN-IT0',
    appId: '1:922472024808:web:1bc53c3792735f2d4bd75d',
    messagingSenderId: '922472024808',
    projectId: 'studyhub-d56f4',
    authDomain: 'studyhub-d56f4.firebaseapp.com',
    storageBucket: 'studyhub-d56f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn2QPTgPRGVdG50wZCLVFPsSG01EOsRNE',
    appId: '1:922472024808:android:92cfa749545f087e4bd75d',
    messagingSenderId: '922472024808',
    projectId: 'studyhub-d56f4',
    storageBucket: 'studyhub-d56f4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-i_VIZBY8ch_4e9ESofx3GKOHNyN-IT0',
    appId: '1:922472024808:web:ed30c21d0d1ac6114bd75d',
    messagingSenderId: '922472024808',
    projectId: 'studyhub-d56f4',
    authDomain: 'studyhub-d56f4.firebaseapp.com',
    storageBucket: 'studyhub-d56f4.firebasestorage.app',
  );
}
